version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQLDB_DATABASE}
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
  app:
    depends_on:
      - mysqldb
    build: .
    env_file:
      - ./.env
    ports:
      - ${APP_LOCAL_PORT}:${APP_DOCKER_PORT}
    environment:
      - DB_HOST=mysqldb
      - DB_PORT=${MYSQLDB_DOCKER_PORT}
      - DB_USER=${MYSQLDB_USER}
      - DB_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - DB_NAME=${MYSQLDB_DATABASE}